<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
	</array>
	<key>name</key>
	<string>Magento Backtrace Message</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(^\#\d*|\&gt;\#\d*)</string>
			<key>name</key>
			<string>keyword.other.backtracemessage</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\s+[a-zA-Z_]+)(\[([a-zA-Z_]+)\])?(\#\w*\#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.backtracemessage</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.backtracemessage</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.line.class.backtracemessage</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(called at)\s+\[(\S+)\]</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.backtracemessage</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.location.backtracemessage</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.php</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\s+\/\S+\:)\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.location.backtracemessage</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.php</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.backtracemessage</string>
	<key>uuid</key>
	<string>519af72c-98b6-4b08-9592-b59c5dd3a7f8</string>
</dict>
</plist>
